export const SET_ALL_COMPANIES = 'SET_ALL_COMPANIES/filters'
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES/filters'
export const SET_ALL_PRODUCTS_LOADING = 'SET_ALL_PRODUCTS_LOADING/filters'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS/filters'
export const SET_FILTER_BY_COMPANY = 'SET_FILTER_BY_COMPANY/filters'
export const SET_FILTER_BY_CATEGORY = 'SET_FILTER_BY_CATEGORY/filters'


//saga types
export const BEGIN_ALL_PRODUCTS_REQUEST = 'BEGIN_ALL_PRODUCTS_REQUEST/filters'
