export const SET_ALL_PRODUCTS_LOADING = 'SET_ALL_PRODUCTS_LOADING/products'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS/products'
export const HANDLE_FETCH_ERROR = 'HANDLE_FETCH_ERROR/products'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS/products'
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING/products'
export const SET_PRODUCT_ID = 'SET_PRODUCT_ID/products'

//saga types
export const BEGIN_ALL_PRODUCTS_REQUEST = 'BEGIN_ALL_PRODUCTS_REQUEST/products'
export const BEGIN_PRODUCT_REQUEST = 'BEGIN_PRODUCT_REQUEST/products'












